clear;
clc;
close all;

%% ============================================================
% PD test inputs
% =============================================================

routing = 1;
loading_steps = 1;

desired_pull_mm = [0 0 10];

tau_initial_N = [0 0 5];

active_tendon = 3;

%% ============================================================
% Run Newtonian PD controller
% =============================================================

[converged, ...
 tau_solution_N, ...
 rX, ...
 tip_position, ...
 obtained_pull_mm, ...
 history] = ...
    Newtonian_PD( ...
        routing, ...
        loading_steps, ...
        desired_pull_mm, ...
        tau_initial_N, ...
        active_tendon);